In [3]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [5]:
print("keys of iris dataset: \n {}".format(iris_dataset.keys()))

keys of iris dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [8]:
print("target_names: \n {}".format(iris_dataset["target_names"]))

target_names: 
 ['setosa' 'versicolor' 'virginica']


In [9]:
print("target_names: \n {}".format(iris_dataset["feature_names"]))

target_names: 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [10]:
print("shape of data: {}".format(iris_dataset["data"].shape))

shape of data: (150, 4)


In [13]:
print("first 5 coloumns of data: \n {} ".format(iris_dataset["data"][:5]))

first 5 coloumns of data: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] 


In [14]:
print("type of target: \n {} ".format(type(iris_dataset["target"])))

type of target: 
 <class 'numpy.ndarray'> 


In [15]:
print("shape of target: \n {} ".format(iris_dataset["target"].shape))

shape of target: 
 (150,) 
